#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'sinatra', require: false
  gem 'sinatra-contrib'
end

require 'sinatra'
require_relative 'helpers'

set :port, 3000

boards = {}
cards = []
100.times do |i|
  cards << { id: 'here', board: 'here', username: "user #{i}", column: ["start", "stop", "continue"].sample, message: "Message is here #{i}", votes: 0 }
end

def board_cards(board, cards)
  cards.select { |c| c[:board] == board }
end

get '/' do
  erb :index
end

post '/username' do
  cookies[:username] = params[:username]
  cookies[:rem_votes] = 3
  redirect "/boards/#{params[:board]}"
end

get '/boards/:board' do
  board = boards[params[:board]]
  redirect '/' unless board

  if cookies[:username]
    erb :board, locals: { board: boards[params[:board]] }
  else
    erb :username, locals: { board: boards[params[:board]] }
  end
end

post '/boards' do
  id = SecureRandom.uuid

  board = params.slice(:name, :columns).merge(id: id)
  board[:columns] = board[:columns].lines.map(&:strip).reject(&:empty?)

  boards[id] = board
  cookies[:rem_votes] = 3
  redirect "/boards/#{id}"
end

get '/boards/:board/cards' do
  board = boards[params[:board]]
  redirect '/' unless board

  erb :cards, locals: { board: boards[params[:board]], cards: board_cards(params[:board], cards) }
end

post '/boards/:board/cards' do
  board = boards[params[:board]]
  card_id = SecureRandom.uuid
  redirect '/' unless board

  card = params.slice(:board, :column, :message).merge(username: cookies[:username]).merge(votes: 0).merge(id: card_id)
  card = JSON.parse(card.to_json, symbolize_names: true)
  cards << card

  redirect "/boards/#{params[:board]}"
end

get '/boards/:board/cards/:card/up_vote' do
  board = params[:board]
  card_id = params[:card]
  card_index = cards.find_index{|card| card[:id] == card_id }
  redirect '/' unless card_id
  redirect "/boards/#{params[:board]}" if cookies[:rem_votes].to_i == 0
  cards[card_index][:votes] += 1
  cookies[:rem_votes] = cookies[:rem_votes].to_i - 1

  redirect "/boards/#{params[:board]}"
end
